export const ACTIONS = {
    ADD_LEVEL_ONE_SENTENCE: "ADD_LEVEL_ONE_SENTENCE",
    ADD_LEVEL_TWO_SENTENCE: "ADD_LEVEL_TWO_SENTENCE",
    ADD_LEVEL_THREE_SENTENCE: "ADD_LEVEL_THREE_SENTENCE",
    ADD_LEVEL_FOUR_SENTENCE: "ADD_LEVEL_FOUR_SENTENCE",
    ADD_LEVEL_FIVE_SENTENCE: "ADD_LEVEL_FIVE_SENTENCE",
    ADD_LEVEL_SIX_SENTENCE: "ADD_LEVEL_SIX_SENTENCE",


    DEL_LEVEL_ONE_SENTENCE: "DEL_LEVEL_ONE_SENTENCE",
    DEL_LEVEL_TWO_SENTENCE: "DEL_LEVEL_TWO_SENTENCE",
    DEL_LEVEL_THREE_SENTENCE: "DEL_LEVEL_THREE_SENTENCE",
    DEL_LEVEL_FOUR_SENTENCE: "DEL_LEVEL_FOUR_SENTENCE",
    DEL_LEVEL_FIVE_SENTENCE: "DEL_LEVEL_FIVE_SENTENCE",
    DEL_LEVEL_SIX_SENTENCE: "DEL_LEVEL_SIX_SENTENCE",

    REPLACE_LEVEL_ONE_SENTENCE: "REPLACE_LEVEL_ONE_SENTENCE",
    REPLACE_LEVEL_TWO_SENTENCE: "REPLACE_LEVEL_TWO_SENTENCE",
    REPLACE_LEVEL_THREE_SENTENCE: "REPLACE_LEVEL_THREE_SENTENCE",
    REPLACE_LEVEL_FOUR_SENTENCE: "REPLACE_LEVEL_FOUR_SENTENCE",
    REPLACE_LEVEL_FIVE_SENTENCE: "REPLACE_LEVEL_FIVE_SENTENCE",
    REPLACE_LEVEL_SIX_SENTENCE: "REPLACE_LEVEL_SIX_SENTENCE",

    SET_ALL_SENTENCES: "SET_ALL_SENTENCES"
}