export const ACTIONS = {
    ADD_LEVEL_ONE_SENTENCE: "ADD_LEVEL_ONE_SENTENCE",
    REPLACE_SENTENCE: "REPLACE_SENTENCE",
    DELETE_SENTENCE: "DELETE_SENTENCE",
    SET_ALL_SENTENCES: "SET_ALL_SENTENCES"
}